project_id = "rclbjiqfabuuhiwxmjwp"

[auth]
site_url = "https://plataformaeleitoral.ia.br"
additional_redirect_urls = [
  "https://plataformaeleitoral.ia.br",
  "https://plataformaeleitoral-ia-paulocardoso-labs-projects.vercel.app/",
  "https://plataformaeleitoral-ia-paulocardoso-labs-projects.vercel.app/**",
  "https://plataformaeleitoral-*-ia-paulocardoso-labs-projects.vercel.app",
  "https://plataformaeleitoral-*-ia-paulocardoso-labs-projects.vercel.app/**",
  "http://127.0.0.1:4173",
  "http://localhost:4173"
]

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true
max_frequency = "1m"
otp_length = 8
otp_expiry = 3600

[auth.mfa.totp]
enroll_enabled = true
verify_enabled = true

[storage.vector]
enabled = false

[functions.dataset]
verify_jwt = false

[functions.tester-access]
verify_jwt = false

[functions.admin-access]
verify_jwt = false
